leetcode_solver/leetcode_solver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

leetcode_solver/main/urls.py
from django.urls import path, include
from main.views import index, problem

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('problem/<str:id>/', problem, name='problem'),
]

leetcode_solver/main/models.py
from django.db import models

# Create your models here.
class Queries(models.Model):
    question_url_slug = models.TextField(null = True)
    question_id = models.IntegerField(null = True)
    difficulty = models.TextField(null = True)
    content = models.TextField(null = True)
    similar_questions = models.TextField(null = True)
    topics = models.TextField(null = True)
    videos = models.TextField(null = True)
    title = models.TextField(null = True)

leetcode_solver/main/views.py
import imp
from multiprocessing import context
from django.http import HttpResponse
from django.shortcuts import render
from main.models import Queries
from django.template.response import TemplateResponse
from django.shortcuts import redirect
import requests
import json
import googleapiclient.discovery
from django.conf import settings
from django.shortcuts import redirect


# YouTube API key
DEVELOPER_KEY = settings.GOOGLE_API_KEY


def index(request):
    # User requests the home page
    if request.method == 'GET':
        return TemplateResponse(request, 'main/index.html', context={"example": "-- some data --", "example2": "-- some other data --"})

    elif request.method == 'POST':
        input_data = request.POST.get('search', False)
        if not input_data:
            return TemplateResponse(request, 'main/index.html', context={"example": "Error!"})

        return redirect(f'/problem/{input_data}')


def problem(request, id):

    # Queries.objects.all().delete()
    failed = False

    # Check if we already have this question's data
    try:
        result = Queries.objects.get(question_id=int(id))
        context = {"id": result.question_id,
                   "title": result.title,
                   "url": result.question_url_slug,
                   "categories": json.loads(result.topics),
                   "difficulty": int(result.difficulty),
                   "content": result.content,
                   "videos": json.loads(result.videos),
                   "relatedQuestions": json.loads(result.similar_questions)[:4]}

        return TemplateResponse(request, 'main/problem.html', context)

    except ValueError:
        try:
            result = Queries.objects.get(question_url_slug=id)
            context = {"id": result.question_id,
                       "url": result.question_url_slug,
                       "title": result.title,
                       "categories": json.loads(result.topics),
                       "difficulty": int(result.difficulty),
                       "content": result.content,
                       "videos": json.loads(result.videos),
                       "relatedQuestions": json.loads(result.similar_questions)[:4]}

            return TemplateResponse(request, 'main/problem.html', context)
        except Queries.DoesNotExist:
            failed = True
    except Queries.DoesNotExist:
        failed = True

    if failed:
        # If we don't have this question's data
        resp = requests.get('https://leetcode.com/api/problems/all/')
        questions = json.loads(resp.content)
        for question in questions['stat_status_pairs']:

            if id == str(question['stat']['question_id']) or id == question['stat']['question__article__slug']:

                paid_only = question['paid_only']

                if not paid_only:
                    print(paid_only)
                    print("--- Getting API Data ---")

                    # Get basic question data
                    question_url_slug = question['stat']['question__article__slug']
                    difficulty = question['difficulty']['level']
                    question_title = question['stat']['question__title']

                    # Get specific question data
                    data = {"operationName": "questionData", "variables": {"titleSlug": question_url_slug}, "query": "query questionData($titleSlug: String!) {\n  question(titleSlug: $titleSlug) {\n    questionId\n    questionFrontendId\n    boundTopicId\n    title\n    titleSlug\n    content\n    translatedTitle\n    translatedContent\n    isPaidOnly\n    difficulty\n    likes\n    dislikes\n    isLiked\n    similarQuestions\n    contributors {\n      username\n      profileUrl\n      avatarUrl\n      __typename\n    }\n    langToValidPlayground\n    topicTags {\n      name\n      slug\n      translatedName\n      __typename\n    }\n    companyTagStats\n    codeSnippets {\n      lang\n      langSlug\n      code\n      __typename\n    }\n    stats\n    hints\n    solution {\n      id\n      canSeeDetail\n      __typename\n    }\n    status\n    sampleTestCase\n    metaData\n    judgerAvailable\n    judgeType\n    mysqlSchemas\n    enableRunCode\n    enableTestMode\n    envInfo\n    libraryUrl\n    __typename\n  }\n}\n"}
                    resp = requests.post(
                        'https://leetcode.com/graphql', json=data).json()

                    try:
                        print(resp)
                        content = resp['data']['question']['content']
                        similar_questions = resp['data']['question']['similarQuestions']
                        topics = resp['data']['question']['topicTags']
                    except:
                        return TemplateResponse(request, 'main/error.html')

                    # Get YouTube API Data
                    SEARCH_QUERY = question_title + \
                        ' Leetcode ' + str(id) + ' Solution'

                    api_service_name, api_version = "youtube", "v3"

                    youtube = googleapiclient.discovery.build(
                        api_service_name, api_version, developerKey=DEVELOPER_KEY)

                    api_request = youtube.search().list(
                        part="id,snippet",
                        type='video',
                        q=SEARCH_QUERY,
                        videoDuration='short',
                        videoDefinition='high',
                        maxResults=4
                    )

                    response = api_request.execute()

                    videos = []
                    for item in response['items']:
                        video_title = item['snippet']['title']
                        video_description = item['snippet']['description']
                        channel_title = item['snippet']['channelTitle']
                        channel_url = 'https://www.youtube.com/channel/' + \
                            item['snippet']['channelId']
                        video_url = 'https://www.youtube.com/embed/' + \
                            item['id']['videoId']
                        thumbnail = item['snippet']['thumbnails']['high']['url']
                        videos.append({"video_title": video_title, 'video_desc': video_description,
                                       "channel_title": channel_title, "channel_url": channel_url, 'video_url': video_url, 'thumbnail': thumbnail})

                    q = Queries(question_id=question['stat']['question_id'], question_url_slug=question_url_slug, difficulty=difficulty,
                                content=content, similar_questions=similar_questions, topics=json.dumps(topics), videos=json.dumps(videos), title=question_title)
                    q.save()

                    return TemplateResponse(request, 'main/problem.html',
                                            context={"id": question['stat']['question_id'],
                                                     "url": question_url_slug,
                                                     "title": question_title,
                                                     "categories": topics,
                                                     "difficulty": difficulty,
                                                     "content": content,
                                                     "videos": videos,
                                                     "relatedQuestions": json.loads(similar_questions)[:4]})
                else:
                    # Handle Premium Question
                    return TemplateResponse(request, 'main/error.html')

        return TemplateResponse(request, 'main/error.html')

leetcode_solver/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- imports -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/styles.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>   
    <script src="https://kit.fontawesome.com/8e52d952f2.js" crossorigin="anonymous"></script>

    <title>Home Page</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><h1>Leetcode Solver</h1></a>
            <button type="button" class="navbar-button btn btn-outline-dark btn-lg ml-auto mr-3" data-toggle="modal" data-target="#signupModal">Student Signup</button>
            <button type="button" class="navbar-button btn btn-outline-dark btn-lg mr-3" data-toggle="modal" data-target="#sponsorModal">Become a Sponsor</button>
            <button type="button" class="navbar-button btn btn-outline-dark btn-lg" data-toggle="modal" data-target="#donateModal">Donate</button>
            <!-- Donate -->
            <div class="modal fade" id="donateModal" tabindex="-1" role="dialog" aria-labelledby="donateModallLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="donateModalLabel">Donate</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                    <p>Upon full deployment this would link to a donation page allowing users to donate to keep the site running.</p>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>

            <!-- Signup -->
            <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="signupModallLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="signupModalLabel">Student Network</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <p>Upon full deployment this would allow students to sign up and join, submit resumes, and get in contact with site sponsors or hiring teams.</p>
                     </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>

            <!-- Sponsor -->
            <div class="modal fade" id="sponsorModal" tabindex="-1" role="dialog" aria-labelledby="sponsorModallLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="sponsorModalLabel">Sponsor Network</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                        <p>Upon full deployment this would allow sponsors to get in contact, arrange hiring opportunites, and bridge the gap between companies and students</p>
                        </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="root-container">
        {% block index %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

leetcode_solver/main/templates/main/error.html
{% extends "main/base.html"%}
{% load static %}
{% block index %}

<div class="error-container">
    <div class="error-message">
        <h1>Error!</h1>
        <h2>This problem is premium-only or does not have enough data...</h2>
        <a href="/"><button type="button" class="navbar-button btn btn-outline-dark btn-lg">Try Again</button></a>
            
    </div>
</div>

{% endblock index %}

leetcode_solver/main/templates/main/index.html
{% extends "main/base.html"%}
{% load static %}
{% block index %}

<link rel="stylesheet" type="text/css" href="{% static 'main/css/search.css' %}" />
<script src="{% static 'main/js/main.js' %}"></script>

<div class="search-container">
    <h1>Explore a Leetcode Question!</h1>
    <div class = "search-buttons"> 
        <div class="button-container">
            <a id="random" href=""><button type="button" class="navbar-button btn btn-outline-dark btn-lg random">Randomize</button></a>
        </div>
        <form class="container" action="{% url 'main:index' %}" method="POST">
            {% csrf_token %}
            <label>
                <input type="number" name="search" required >
                <input type="submit" hidden />
                <ul>
                <li s>s</li>
                <li e>e</li>
                <li a>a</li>
                <li r>r</li>
                <li c>c</li>
                <li h>h</li>
                </ul>
            </label>
        </form>
    </div>


</div>

{% endblock index %}

leetcode_solver/main/templates/main/problem.html
{% extends "main/base.html"%}
{% load static %}
{% block index %}

<link rel="stylesheet" type="text/css" href="{% static 'main/css/problem.css' %}" />

<div class="problem-view-container">
    <div class="sidebar p-5">
       <h2>Category Deep Dives</h2>
       <div class="buttons-container mt-4">
           {% for cat in categories %}
                <button type="button" class="btn btn-light btn-lg mt-3" data-toggle="collapse" data-target="#{{cat.slug}}" aria-expanded="false" aria-controls="{{cat.slug}}">{{cat.name}}</button>
                <div id="{{cat.slug}}" class="collapse">
                    <div class="card card-body">
                      {% if cat.name == "Array" %}
                        <p>
                        An array is a container object that holds a fixed number of values of a single type. The length of an array is established when the array is created. After creation, its length is fixed. You have seen an example of arrays already, in the main method of the "Hello World!" application. This section discusses arrays in greater detail.

                        Illustration of an array as 10 boxes numbered 0 through 9; an index of 0 indicates the first element in the array
                        An array of 10 elements.
                        
                    
                        Each item in an array is called an element, and each element is accessed by its numerical index. As shown in the preceding illustration, numbering begins with 0. The 9th element, for example, would therefore be accessed at index 8.
                        </p>
                        {% elif cat.name == "Hash Table" %}
                        <p>
                            Hash Table is a data structure which stores data in an associative manner. In a hash table, data is stored in an array format, where each data value has its own unique index value. Access of data becomes very fast if we know the index of the desired data.

Thus, it becomes a data structure in which insertion and search operations are very fast irrespective of the size of the data. Hash Table uses an array as a storage medium and uses hash technique to generate an index where an element is to be inserted or is to be located from.
                        </p>
                        {% elif cat.name == "Sliding Window" %}
                        <p>
                            Window Sliding Technique

        The technique can be best understood with the window pane in bus, consider a window of length n and the pane which is fixed in it of length k. Consider, initially the pane is at extreme left i.e., at 0 units from the left. Now, co-relate the window with array arr[] of size n and pane with current_sum of size k elements. Now, if we apply force on the window such that it moves a unit distance ahead. The pane will cover next k consecutive elements. 
        Consider an array arr[] = {5, 2, -1, 0, 3} and value of k = 3 and n = 5
        Applying sliding window technique : 

        1. We compute the sum of first k elements out of n terms using a linear loop and store the sum in variable window_sum.
        2. Then we will graze linearly over the array till it reaches the end and simultaneously keep track of maximum sum.
        3. To get the current sum of block of k elements just subtract the first element from the previous block and add the last element of the current block.
                        </p>
                        {% elif cat.name == "String" %}
                        <p>
                            A string is a sequence of characters. In other words, a string is an array of character data type. An instance of a string is called a string literal. For instance in C++: string s = "HackerEarth";  is a string literal.

String Manipulation is a class of problems where a user is asked to process a given string and use/change its data. 
                        </p>
                        {% else %}
                        <p> Content coming soon.</p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
       </div>
    </div>

    <div class="problem-container container-fluid">   
        <div class="title-container">
            <h2 class="problem-title">Leetcode Problem #{{ id }}: {{ title }}</h2>
            <div class="categories-container">
                {% for cat in categories %}
                    <span class="badge badge-pill badge-info mr-2">{{ cat.name }}</span>
                {% endfor %}
            </div>
            <h5 class="mt-4">
                Difficulty Level: 
                {% if difficulty == 1 %}<span class="easy-tag">Easy</span>
                {% elif difficulty == 2 %}<span class="medium-tag">Medium</span>
                {% else %}<span class="hard-tag">Hard</span>{% endif %}
            </h5>
        </div>
        <hr>
        <div class="video-demonstrations-container row mt-1 py-1">
            <div class="showcased-video col-9">
                {% with videos|first as showcasedVideo %}
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src={{ showcasedVideo.video_url }}></iframe>
                </div>
                <div class="video-title-attempt-btn-container">
                    <h2 class="mt-4">{{ showcasedVideo.video_title }}</h2>
                    <button type="button" class="navbar-button btn btn-dark btn-md mt-3 px-5"><a style="color:#fff" href="https://leetcode.com/problems/{{ url }}/">Ready To Attempt</a></button>
                </div>
                <hr>
                <div class="description-container">
                    <div class="row">
                    <h2 class="mt-4 ml-4 w-100"> Related Questions </h2>
                    {% for question in relatedQuestions %}
                        <div class="col-sm-6 mt-3">
                            <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ question.title }}</h5>
                                {% if question.difficulty == "Easy" %}<span class="easy-tag" style="font-size: 1.2rem;">Easy</span><br>
                                {% elif question.difficulty == "Medium" %}<span class="medium-tag" style="font-size: 1.2rem;">Medium</span><br>
                                {% else %}<span class="hard-tag" style="font-size: 1.2rem;">Hard</span><br>{% endif %}<br>
                                <a href="/problem/{{ question.titleSlug }}" class="navbar-button btn btn-dark btn-md mt-0">Try It</a>
                            </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
                {% endwith %}
            </div>
            <div class="related-videos-container col-3">
                <h3>More related videos</h4>
                {% with relatedVideos=videos|slice:"1:" %}
                {% for vid in relatedVideos %}
                    <a href="{{vid.video_url}}">
                        <div class="related-video p-3">
                            <p class="h6">{{ vid.video_title }}</p>
                            <img src={{ vid.thumbnail }} class="img-thumbnail">
                        </div>
                    </a>
                {% endfor %}
                {% endwith %}
            </div>
        </div>
    </div>
</div>

{% endblock index %}